### ISSUE TITLE
create and deploy simple version of registry on layer-2

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/mad-hatter#1]
# Bounty
create a simple version of the global rights registry. 

## Scope
- create an ERC721 token contract that can hold movies
- put the imbd-id of related movie into token-id (example: `tt5516972`)
- add id-type attribute as first byte of token-id

## Deliverables
- deployed token contract
- documentation to read and write from contract

## Roles
bounty gardener: @johannbarbie / 42%
bounty worker: @troggy / 43%
bounty reviewer: name / 15%

**Comment by Right2Rebel** [comment]
should have more IDs than just IMDB?

**Comment by troggy** [comment]
@Right2Rebel we want to support different IDs, that's why we are adding id-type byte — to denote which ID is used in this particular token. This way we can use different IDs in future, yet support old/legacy tokens

**Comment by Right2Rebel** [comment]
@johannbarbie @troggy we are now setting up a Workshop prior to creating registry.... 

when are you most available this week?

**Comment by kosta** [comment]
Are you sure you have the right @kosta?

**Comment by johannbarbie** [comment]
> Are you sure you have the right @kosta?

nope, but nice to meet the real @kosta 👏

**Comment by mwaa** [comment]
Review:

- [x] MovieToken Contract available and deployed
- [x] ID-Type attribute as first byte-id
- [x] Test for minting Token
- [ ] Documentation on using contract

@johannbarbie missing simple documentation to read/write from contract

**Comment by johannbarbie** [comment]
good point. maybe i should add that to the readme
