### ISSUE TITLE
App should detect the user payed for the movie already

### ISSUE THREAD

**Issue by troggy** [leapdao/mad-hatter#19]
Streaming site: 
- if paid, `paymentRequest` should resolve without user interaction, so that user experience is seamless
- otherwise, proceed with normal payment flow

MoviePage in app:
- app should show the movie is paid already for the account.

## Scope
- when sending payment insert movie tokenId in a `message` for tx
- when payment is requested, the WR App should check if the user have already paid for the movie. For now, we can scan user's tx history for transfers to movie "owner" with movie tokenId in a `message` field. Store the payment information into localStorage so next time it is available faster.
- if movie is paid already, WR app should:
  - show the appreciation screen: positive message that streamer did a good. Add "Dismiss" button to close the WR app in this case plus close it automatically after a while.
  - communicate "success" payment status back to the streaming site
  - show the appreciation message, if opened directly without iframe

## Deliverables
- updated WR app
- (optionally) updated example site

## Roles

gardener: @troggy 50 DAI
worker: 80% @mwaa 
reviewer: 20% @Clearwood

**Comment by johannbarbie** [comment]
> if paid, paymentRequest should resolve without user interaction, so that user experience is seamless

does that also close the wallet popup then?

> MoviePage in app:
> app should show the movie is paid already for the account.

so if a user clicks a movie that was paid before, the wallet scans the history of transactions, shows that the payment has ben done already, and gives the user a "back to watching the movie" button?

**Comment by troggy** [comment]
> does that also close the wallet popup then?

I'd say popup is not needed at all in this case

> so if a user clicks a movie that was paid before, the wallet scans the history of transactions, shows that the payment has ben done already, and gives the user a "back to watching the movie" button?

Not sure if "back to watching the movie" button is possible, because the app is not aware about streaming platforms. It will be possible once "Rabbit Hole" is done

**Comment by Right2Rebel** [comment]
Rabbit Hole 1.0 is in spec? - ie access to move paid and free behind the scenes... 

Some popup should verify acknowledgement of movie already paid - "thanks for being a responsible rebel" or something in that order - positive message

**Comment by troggy** [comment]
> Rabbit Hole 1.0 is in spec?

no, not in spec

**Comment by Right2Rebel** [comment]
Yes in spec.

Alan R. Milligan
CEO & Founder
+47 9285 9197

**Comment by Right2Rebel** [comment]
> > Rabbit Hole 1.0 is in spec?
> 
> no, not in spec

we should review spec
