### ISSUE TITLE
Vital cosmetic UX fix

### ISSUE THREAD

**Issue by Right2Rebel** [leapdao/mad-hatter#44]
Issue #1: when WR was a plug-in it integrated smoothly with the PSS/audience browser drop down. 
Proposal: can we force the stream to go full screen on play; play for 5-7 seconds before drop down (identification time); drop down into full screen of film

Issue #2: drop down should be movie poster size / ratio 
Proposal: change to 27" x 40" ratio

Issue #3: payment time confirmation time 
Proposal: max 3 seconds (now 4)

Issue #4: change thumbs up above "Thank you for being a responsible rebel" 
Proposal: White Rabbit logo instead of a thumb and hold for 1 second longer

## Scope

- [x] streamer: show video stream full-screen
- [x] streamer: request payment in 7 seconds (implemented in #43)
- [x] app: use poster ratio (27/40) for app size
- [x] app: use White Rabbit logo on Acknowledgement page instead of big emoji
- [x] app: keep Acknowledgement page open for 4 seconds (not 3 seconds as it is now)

## Roles

gardener: @troggy 30 DAI
worker: @troggy (#43 only) + @Clearwood
reviewer: @troggy

**Comment by troggy** [comment]
> Issue #3: payment time confirmation time
> Proposal: max 3 seconds (now 4)

we cannot influence this much at this step as this depends on the network blocktime (5 seconds for xdai). However, we can make it _appear_ faster for user by showing Acknowledgement page earlier before tx is settled.

**Comment by Clearwood** [comment]
If we use the browser embedded full screen option we can not display the drop down over the fullscreen.

**Comment by troggy** [comment]
> However, we can make it appear faster for user by showing Acknowledgement page earlier before tx is settled.

It will make UX possibly confusing (imaging tx got rejected and you've seen confirmation screen already) — I don't think it worth one extra second.

Let's keep 3 seconds requirement in mind for when we will be using some proper network (not xdai)
