### ISSUE TITLE
architect and spec a collection pool

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/mad-hatter#50]
# Bounty

A collection pool receives all the payments from the audience. Each payment has 3 tags attached:
1. **movieId** - an Identifier for the movie
2. **region** - a ISO_3166-1 numeric code of the position of the audience
3. **window** - a short string like 'cinema' or 'vod' to describe the delivery window

The payment is stored in the pool, so that it can be:
- either forwarded to a payment waterfall according to proven destination information from the registry contract, or
- returned to the audience, if within a period of 3 month no rights-holder could be identified and inserted into the registry.

![Collection Pool Design](https://user-images.githubusercontent.com/659301/79572649-9aa68500-80bd-11ea-8f8a-21bd79636178.png)

## Scope

- extend on [drawing](https://docs.google.com/drawings/d/15WQR1dk-Go-_jPvH8OuEeZpG_6LWMgbEbXro6gpOlZA)
- create an architecture document
- list problems and possible improvements

## Deliverables

- design document
- implement a mock contract for wallet with owned backend

## Funding Circle

- wr-escrow

## Bounty Owner/Gardener

@johannbarbie  as **RepLink**

## Roles
bounty gardener: @johannbarbie  / 50 DAI
bounty worker: @johannbarbie  / 390 DAI
bounty reviewer: @Clearwood  / 110 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty

**Comment by Right2Rebel** [comment]
Just to be detailed on one point - correct that the revenue will be "returned to the audience" as explained above but not "reclaimable by users" as written in the drawing. that process needs to be on our side/rights holder side and defined by a certain time period TBD.

**Comment by johannbarbie** [comment]
@Clearwood here is the design doc as part of the issue: https://docs.google.com/document/d/1RMQJlHxetuik1a0OqKXeI8UY9ZebdNzHf5LocN-U3R0
