### ISSUE TITLE
Wallet should support a movie link

### ISSUE THREAD

**Issue by troggy** [leapdao/mad-hatter#6]
## Scope
- wallet should support a route like `wallet.leap.rocks/title/<tokenId>` where `tokenId` is a NFT token representing a movie
- when opened, it should:
   - read `imdb id` from `tokenId`
   - get movie title and poster link from themoviedb.org API. Add it to client library as a `getMovieMetadata(imdbId, themovedbApiKey)` function.
   - display title, poster and pay button
- pay button should init payment to the token owner
- for now, the payment amount is fixed and is $2.

## Deliverables
- updated wallet code
- updated client library
- client library published on npm

## Roles
gardener: @troggy | 10%
worker: @troggy | 70%
reviewer: @johannbarbie  | 20%

**Comment by troggy** [comment]
Requires https://github.com/leapdao/mad-hatter/issues/3

**Comment by Right2Rebel** [comment]
note former mock ups: should display director, actors, rights holders in territory

**Comment by troggy** [comment]
✅director
✅actors
❓rights holders in territory

@Right2Rebel which territory? Visitor or streaming site?

**Comment by troggy** [comment]
spinned off the issue here: https://github.com/leapdao/mad-hatter/issues/22

**Comment by Right2Rebel** [comment]
Streamer not streaming site, ie country where its watched and paid.

Alan R. Milligan
CEO & Founder
+47 9285 9197
