### ISSUE TITLE
Receive payment result on a streaming site

### ISSUE THREAD

**Issue by troggy** [leapdao/mad-hatter#8]
## Scope
- wallet should communicate payment status to caller window (if wallet is opened in iframe):
  - success message if payment succeed (with movie id)
  - fail message if user rejected tx or otherwise didn't pay (e.g. out of money)
- change client library API: `requestPayment` should return Promise which resolves on successful payment and rejects otherwise.
- `requestPayment` should close the iframe on completion

## Deliverables
- updated wallet code
- updated client library code
- new client library version published on npm
- updated README with client library docs

## Roles
gardener: @troggy | 40%
worker: @Clearwood  | 40%
reviewer: @johannbarbie  | 20%

**Comment by johannbarbie** [comment]
done
