### ISSUE TITLE
Adjust streaming site to work with new client library

### ISSUE THREAD

**Issue by troggy** [leapdao/mad-hatter#9]
## Scope
- change previous version of the streaming site (originally from [here](https://github.com/motion-protocol/streaming-site), should be in our monorepo at this point) to use the client library to request payment
- upload couple of movie teasers to S3
- mint MovieToken's for the test movies. Use existing MovieToken contract instance on xdai chain
- change streaming site to read the movies metadata using `WhiteRabbitClient#getMovieData`. Hardcode the list of `[imdbId, link to S3]` for now.

## Deliverables
- updated streaming site
- MovieTokens minted on xdai chain

**Comment by Right2Rebel** [comment]
For beta testing we are going to need real movies and an attractive streaming site - when we can demo solution it may be time to talk with Stremio

**Comment by troggy** [comment]
> we are going to need real movies

@Right2Rebel which movies we can use for the demo? Those from K5 company (like "Paterson")?

**Comment by troggy** [comment]
From the today's call:
- we can use K5 movies. Alan to double check that
- we can use just trailers, but full movies will be even better
